App\Entity\Categoria:
  attributes:
    id:
      groups: ['post_categoria', 'get_categoria', 'up_categoria', 'get_restaurante', 'rest_filtered']

    categoria:
      groups: ['get_categorias', 'post_categoria', 'get_categoria', 'up_categoria', 'get_restaurante', 'rest_filtered']