App\Entity\Cliente:
  attributes:
    id:
      groups: ['post_cliente', 'get_cliente', 'up_cliente', 'get_dir', 'post_dir']

    nombre:
      groups: ['post_cliente', 'get_cliente', 'up_cliente', 'get_dir', 'post_dir']

    apellidos:
      groups: ['post_cliente', 'get_cliente', 'up_cliente', 'get_dir', 'post_dir']

    telefono:
      groups: ['post_cliente', 'get_cliente', 'up_cliente', 'get_dir', 'post_dir']

    direcciones:
      groups: []

    pedidos:
      groups: []
