App\Entity\Municipios:
  attributes:
    id:
      groups: ['post_dir', 'get_dir','get_dir_cliente', 'get_municipios']
    municipio:
      groups: ['post_dir', 'get_dir','get_dir_cliente', 'get_municipios']