App\Entity\Provincias:
  attributes:
    id:
      groups: ['post_dir', 'get_dir', 'up_dir', 'get_dir_cliente', 'get_provincias' ]
    provincia:
      groups: ['post_dir', 'get_dir', 'up_dir', 'get_dir_cliente', 'get_provincias' ]